name: RockPaperScissorsPlus
options:
  bundleIdPrefix: com.pixelatedstudios
settings:
  PRODUCT_BUNDLE_IDENTIFIER: com.pixelatedstudios.RockPaperScissorsPlus
  SWIFT_VERSION: 6.0
  IPHONEOS_DEPLOYMENT_TARGET: 18.0
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: QA99U7Y63B
  INFOPLIST_FILE: RockPaperScissorsPlus/Info.plist
targets:
  RockPaperScissorsPlus:
    type: application
    platform: iOS
    sources:
      - path: RockPaperScissorsPlus
    resources: []
    settings:
      